default: wb32-run

profiles:
  wb32-run:
    build_test_disk: false
    harddrive: ${NIO_WORKSPACE}/images/amigaos3.2-run.vhd
    kickstart: ${AMIGA_WB32_KICKSTART}
    config_file: ${NIO_WORKSPACE}/configs/amiga/base-68030.uae

  wb1.3:
    disk: ${AMIGA_WB13_ADF_WORKBENCH}
    kickstart: ${AMIGA_WB13_KICKSTART}
    settings:
      chipmem_size: 512
      fastmem_size: 0
      cpu_compatible: true
      cachesize: 0
