machine:
  system: 800xl
  video: pal
  ram_kb: 1088
  kernel: xl
  basic: false
  sio_patch: false
  accurate_disk: true

altirra:
  settings_template: configs/atari/settings/altirraSDL-settings.ini
  rom_roots:
    os: ${ATARI_OS_ROMS}
    basic: ${ATARI_BASIC_ROMS}
  profile: null
  portable: false
  debug: false
  netsio_command_ack_delay_tics: 1800
  debug_commands: []
  devices:
    - type: custom
      params:
        hotreload: false
        path: ${FUJINET_EMULATOR_BRIDGE}/altirra-custom-device/netsio.atdevice
        allowunsafe: false
  host_paths:
    - mode: rw
      path: ${NIO_APPS_ATARI_BIN}

startup:
  program: ${NIO_APPS_ATARI_BIN}/fdrive.xex

  # disks:
  #   - ${ATARI_DOS_BOOT_DISK}
